version: '3.8'
services:
  c-service:
    build: 1. C (Fri)
    container_name: gpbu-c
    volumes:
      - ./1. C (Fri):/workspace
    tty: true
    stdin_open: true
    command: bash

  db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: score
    ports:
      - "5432:5432"